name: CI pipeline
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
        - name: Printing a message
          run: echo "Hello, World!"  
        - name: Show Current time
          run: date
        - name: List files
          run: ls -la  
        - name: Print Workflow event
          run: echo "${{ github.event_name }}"
        - name: Show GitHub workspace
          run: echo "${{ github.workspace }}"
        - name: Show Runner OS
          run: echo "${{ runner.os }}"
        - name: Show Github Repository
          run: echo "${{ github.repository }}"  